config/routes.rb
Spectrum::Application.routes.draw do
  
	root to: 'spectrum_ranges#index' 
  resources :spectrum_ranges
	resources :agencies

	resources :agency_actions
	resources :issues do
		resources :agency_actions
		resources :agencies
	end

end

app/models/spectrum_range.rb
# == Schema Information
#
# Table name: spectrum_ranges
#
#  id         :integer          not null, primary key
#  low        :integer
#  high       :integer
#  issue_id   :integer
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SpectrumRange < ActiveRecord::Base
	before_save :default_values
  attr_accessible :high, :issue_id, :low, :name, :share
  default_scope order('low ASC')
  
 	belongs_to :issue	
  def width
		high - low
  end
	def default_values
		self.share ||= 1
	end
end

app/controllers/spectrum_ranges_controller.rb
class SpectrumRangesController < ApplicationController
  # GET /spectrum_ranges
  # GET /spectrum_ranges.json
  def index
    @spectrum_ranges = SpectrumRange.includes(:issue).all
		@spectrum_counter = SpectrumRange.minimum('low')
		@range_width = SpectrumRange.maximum('high') - SpectrumRange.minimum('low')
		@multirow = 1
		@spectrum_labels = Hash.new
		@spectrum_labels[@spectrum_counter] = 24
		@issues= Issue.all
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spectrum_ranges }
    end
  end

  # GET /spectrum_ranges/1
  # GET /spectrum_ranges/1.json
  def show
    @spectrum_range = SpectrumRange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spectrum_range }
    end
  end

  # GET /spectrum_ranges/new
  # GET /spectrum_ranges/new.json
  def new
    @spectrum_range = SpectrumRange.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spectrum_range }
    end
  end

  # GET /spectrum_ranges/1/edit
  def edit
    @spectrum_range = SpectrumRange.find(params[:id])
  end

  # POST /spectrum_ranges
  # POST /spectrum_ranges.json
  def create
    @spectrum_range = SpectrumRange.new(params[:spectrum_range])

    respond_to do |format|
      if @spectrum_range.save
        format.html { redirect_to @spectrum_range, notice: 'Spectrum range was successfully created.' }
        format.json { render json: @spectrum_range, status: :created, location: @spectrum_range }
      else
        format.html { render action: "new" }
        format.json { render json: @spectrum_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spectrum_ranges/1
  # PUT /spectrum_ranges/1.json
  def update
    @spectrum_range = SpectrumRange.find(params[:id])

    respond_to do |format|
      if @spectrum_range.update_attributes(params[:spectrum_range])
        format.html { redirect_to @spectrum_range, notice: 'Spectrum range was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spectrum_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spectrum_ranges/1
  # DELETE /spectrum_ranges/1.json
  def destroy
    @spectrum_range = SpectrumRange.find(params[:id])
    @spectrum_range.destroy

    respond_to do |format|
      format.html { redirect_to spectrum_ranges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spectrum_ranges_helper.rb
module SpectrumRangesHelper
end

app/views/spectrum_ranges/_empty_range.html.erb
<div class="empty-range">
</div>

app/views/spectrum_ranges/_form.html.erb
<%= label_tag :spectrum_range, "Spectrum Band:" %>
<span class="input-append">
	<%= text_field_tag :range_low, nil, id: "spectrum-low" %><span class="add-on">MHz</span>
</span>	
- 
<span class="input-append">
	<%= text_field_tag :range_high, nil, id: "spectrum-high" %><span class="add-on">MHz</span>
</span>
<div class="spectrum-range"></div>

app/views/spectrum_ranges/_spectrum_labels.html.erb
<% @spectrum_labels[@spectrum_counter]=24 %>
<% @spectrum_labels.each {|key, value| %>
	<div class="band-label" style="width:<%=value%>px;">[<%=key%>]</div>
<% } %>

app/views/spectrum_ranges/_spectrum_range.html.erb
<div class="range" style="background-color:<%= spectrum_range.issue.color %>; height: <%= bandHeight %>px;" data-id="<%=spectrum_range.issue.id %>" data-name="<%=spectrum_range.issue.name %>" data-description="<%=spectrum_range.issue.description %>" data-agencies="<%= issue_agency_actions_path(spectrum_range.issue.id, format: :json) %>">
	<p class="text-center"><%= spectrum_range.name %></p>
</div>

app/views/spectrum_ranges/edit.html.erb
<h1>Editing spectrum_range</h1>

<%= render 'form' %>

<%= link_to 'Show', @spectrum_range %> |
<%= link_to 'Back', spectrum_ranges_path %>

app/views/spectrum_ranges/index.html.erb
<div id="information">
	<dl>
		<dt class="info-title">Instructions</dt>
		<dd class="info-description">Click a spectrum band for more information.</dd>
		<dd class="info-agencies"></dd>
	</dl>
	<div id="add-action">
	</div>
<table class="table table-bordered table-hover">
	<thead>
		<tr>
   	 <th>Name</th>
    	<th>Description</th>
	  </tr>
	</thead>
	<tbody>
		<% @issues.each do |issue| %>
			<tr class="range" data-agencies="<%= issue_agency_actions_path(issue.id, format: :json) %>" data-id="<%= issue.id %>" data-name="<%= issue.name %>" data-description="<%= issue.description %>" data-agencies="<%= issue_agencies_path(issue.id, format: :json) %>">
  	  <td><%= issue.name %></td>
    	<td><%= issue.description %></td>
	  </tr>
		<% end %>
	</tbody>
</table>
</div>
<div class="row">
<% @spectrum_ranges.each do |spectrum_range| %>
	<% bandWidth = spectrum_range.width/@range_width.to_f * 900 %>
	<% bandHeight = 100 / spectrum_range.share %>

	<% if @spectrum_counter != spectrum_range.low && @multirow == 1 %>
		<div class="range-block" style="width:<%= (spectrum_range.low-@spectrum_counter)/@range_width.to_f * 900 %>px;">
			<%= render 'empty_range', bandWidth: bandWidth %>
			<div class="range-label"><%=@spectrum_counter%></div>
			<% @spectrum_counter = spectrum_range.low %>
		</div>
	<% end %>

	<% if spectrum_range.share == 1 %>
		<div class="range-block" style="width:<%= bandWidth %>px;">
			<%= render spectrum_range, bandWidth: bandWidth, bandHeight: bandHeight %>
			<div class="range-label"><%=spectrum_range.low%></div>
		</div>
		<% @multirow = 0 %>
		<% @spectrum_counter = spectrum_range.high %>
	<% elsif @multirow == 1 %>
		<div class="range-block" style="width:<%= bandWidth %>px;">
			<%= render spectrum_range, bandWidth: bandWidth, bandHeight: bandHeight %>
		<% @multirow += 1 %>
		<% @spectrum_counter = spectrum_range.high %>
	<% else %>
		<%= render spectrum_range, bandWidth: bandWidth, bandHeight: bandHeight %>
		<% if @multirow == spectrum_range.share %> 
			<% @multirow = 1 %>
			<div class="range-label"><%= spectrum_range.low %></div>
			</div>
		<% else %>
			<% @multirow += 1 %>
		<% end %>
	<% end %>
<% end %>
<div class="range-label" style="float:right;"><%= SpectrumRange.maximum("high") %></div>
<br />

<%= link_to 'Add New Area of Interest', new_issue_path %>
</div>

app/views/spectrum_ranges/new.html.erb
<h1>New spectrum_range</h1>

<%= render 'form' %>

<%= link_to 'Back', spectrum_ranges_path %>

app/views/spectrum_ranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Low:</b>
  <%= @spectrum_range.low %>
</p>

<p>
  <b>High:</b>
  <%= @spectrum_range.high %>
</p>

<p>
  <b>Issue:</b>
  <%= @spectrum_range.issue_id %>
</p>

<p>
  <b>Name:</b>
  <%= @spectrum_range.name %>
</p>


<%= link_to 'Edit', edit_spectrum_range_path(@spectrum_range) %> |
<%= link_to 'Back', spectrum_ranges_path %>