config/routes.rb
Spectrum::Application.routes.draw do
  
	root to: 'spectrum_ranges#index' 
  resources :spectrum_ranges
	resources :agencies

	resources :agency_actions
	resources :issues do
		resources :agency_actions
		resources :agencies
	end

end

app/controllers/agency_actions_controller.rb
class AgencyActionsController < ApplicationController
  # GET /agency_actions
  # GET /agency_actions.json
  def index
		@issue = Issue.find(params[:issue_id])
    @agency_actions = @issue.agency_actions
			
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agency_actions.as_json }
    end
  end
	def new
		@issue = Issue.find(params[:issue_id])
		@agencies = Agency.all
		@agency_action = @issue.agency_actions.new
		respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agency_actions.as_json }
    end
	end
	def create
		@issue = Issue.find(params[:issue_id])
    @agency_action = @issue.agency_actions.new(params[:agency_action])

    respond_to do |format|
      if @agency_action.save
        format.html { redirect_to @agency_action, notice: 'Agency Action was successfully created.' }
        format.json { render json: @agency_action, status: :created, location: @agency_action }
      else
        format.html { render action: "new" }
        format.json { render json: @agency_action.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/views/agency_actions/_form.html.erb
<%= form_for [@issue, @agency_action], html: {class: "form-horizontal"} do |f| %>
  <% if @agency_action.errors.any? %>
    <div id="error_explanation>
      <h2><%= pluralize(@agency_action.errors.count, "error") %> prohibited this agency action from being saved:</h2>
      <ul>
      <% @agency_action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="control-group">
		<%= f.label :agency_id, class: "control-label" %>
		<div class="controls">
			<%= f.select :agency_id, options_from_collection_for_select(@agencies, :id, :name), class: "input-xlarge" %>
		</div>
	</div>
	<div class="control-group">
    <%= f.label :description, class: "control-label" %>
		<div class="controls">
			<%= f.text_area :description, class: "input-xlarge" %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :action_date, class: "control-label" %>
		<div class="controls">
			<%= f.date_select :action_date %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :link, class: "control-label" %>
		<div class="controls">
			<%= f.text_field :link, class: "control-label" %>
		</div>
	</div>
	<%= hidden_field_tag :issue_id %>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/agency_actions/new.html.erb
<h1>New Agency Action</h1>

<%= render 'form' %>

<%= link_to 'Back', agency_actions_path %>