config/routes.rb
Spectrum::Application.routes.draw do
  
	root to: 'spectrum_ranges#index' 
  resources :spectrum_ranges
	resources :agencies

	resources :agency_actions
	resources :issues do
		resources :agency_actions
		resources :agencies
	end

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :name
	has_many :agency_actions
	has_many :issues, through: :agency_actions
end

app/models/agency_action.rb
class AgencyAction < ActiveRecord::Base
  attr_accessible :agency_id, :description, :link
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agencies }
    end
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @agency = Agency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/new
  # GET /agencies/new.json
  def new
    @agency = Agency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/1/edit
  def edit
    @agency = Agency.find(params[:id])
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(params[:agency])

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render json: @agency, status: :created, location: @agency }
      else
        format.html { render action: "new" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agencies/1
  # PUT /agencies/1.json
  def update
    @agency = Agency.find(params[:id])

    respond_to do |format|
      if @agency.update_attributes(params[:agency])
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy

    respond_to do |format|
      format.html { redirect_to agencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<h1>Listing agencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agencies.each do |agency| %>
  <tr>
    <td><%= agency.name %></td>
    <td><%= link_to 'Show', agency %></td>
    <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
    <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @agency.name %>
</p>


<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>